name: Process building feature (TestNet)

on:
  schedule:
  - cron: '0 * * * *'

  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.ref_name }}

jobs:
  process_deposits:
    name: Run building feature worker
    runs-on: ubuntu-latest
    env:
      MANAGER_PASSPHRASE: ${{ secrets.BUILD_MANAGER_PASSPHRASE }}
      LEDGER_TYPE: TestNet

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.2.0
        with:
          poetry-version: 1.3.2

      - name: Install python dependencies
        run: poetry install

      - uses: pre-commit/action@v3.0.0
        name: "Linters and formatters check"
        with:
          extra_args: --all-files --show-diff-on-failure

      - name: Fetch new cities
        run: |
          PYTHONPATH="." poetry run python src/build/process_build.py

      - name: Process AWT Deposits
        run: |
          PYTHONPATH="." poetry run python src/build/fetch_tiles.py

      - name: Commit files
        id: commit_files
        if: always()
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "chore: refreshed building data 🤖" -a
            echo "HAS_COMMITS=true" >> "$GITHUB_ENV"
          else
            echo "no changes - skipping "
            echo "HAS_COMMITS=false" >> "$GITHUB_ENV"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        if: env.HAS_COMMITS != false
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
